### ISSUE TITLE
fails when pull_request is undefined

### ISSUE THREAD

**Issue by airtonix** [marocchino/checkbox-action#148]
~~For some two functions attempting to get `body` are failing because `github.context.payload.pull_request` is undefined.~~

When the PR body hasn't changed from its original state, this function fails because `changes.body.from` doesn't exist on the context until changes are made to the PR body.

https://github.com/marocchino/checkbox-action/blob/main/src/detect.ts#L7

![image](https://github.com/marocchino/checkbox-action/assets/61225/d1230e46-3310-4664-a1c5-79900f816d93)

workflow: 

```yml
name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  DetectCheckboxes:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - uses: marocchino/checkbox-action@v1
        id: detect
        with:
          action: 'detect'

  PrintCheckboxes:
    needs: DetectCheckboxes
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{needs.detect.outputs.checked}}

  LintPrTitle:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The PR template : 

```md
# Description

## What kind of change is this?

- [ ] bug fix
- [ ] documentation
- [ ] new feature

## Steps to test changes

<!-- 
It's important that changes proposed are able to be verified by others.
Provide enough information for others to follow. Screenshots are welcome.
//-->

1. Build the app with `command to build`
2. Run the app with `./build/lamp --required-args`
3. Configure the app ...
4. Do this in the app ...
5. Then this ...
6. Observe this in the app ... to confirm changes.
```
